import UIKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
  var window: UIWindow?

  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    let lynxEnv = LynxEnv.sharedInstance()
    let config = LynxConfig(provider: TemplateProvider())
    
    // Register new modules with:
    // config.register(YourModuleName.self)

    // Generated by cocoapods-lynx-library; without this the stack fails with
    // LynxCreateUIException. Android gets it through autolink.
    LynxGeneratedLibraryRegistry().setup(config)

    lynxEnv.prepareConfig(config)
    
    return true
  }
}
