import UIKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
  var window: UIWindow?

  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    let lynxEnv = LynxEnv.sharedInstance()
    let config = LynxConfig(provider: TemplateProvider())
    
    // Register new modules with:
    // config.register(YourModuleName.self)

    // Generated by cocoapods-lynx-library; without this the stack fails with
    // LynxCreateUIException. Android gets it through autolink.
    LynxGeneratedLibraryRegistry().setup(config)

    lynxEnv.prepareConfig(config)

    enableDevTool(lynxEnv)

    return true
  }

  private func enableDevTool(_ lynxEnv: LynxEnv) {
    // Required for the DevTool desktop app to see this app at all.
    DebugRouter.instance().enableAllSessions()

    lynxEnv.lynxDebugEnabled = true
    lynxEnv.devtoolEnabled = true
    lynxEnv.logBoxEnabled = true
  }
}
